name: DotNetPad
on:
  push:
    paths: 
      - 'src/**'
      - '.github/workflows/**'

jobs:
  build:
    name: 🛠️ Build and test
    runs-on: windows-2025

    steps:      
    - name: 🔖 Check-out
      uses: actions/checkout@v6
  
    - name: ⚙️ Setup MSBuild
      uses: microsoft/setup-msbuild@v3
    
    - name: 🛠️ Build
      run: msbuild ./src/DotNetPad/DotNetPad.slnx /restore /p:Configuration=Release /p:GenerateAppxPackageOnBuild=false
